name: Release

on:
  push:
    branches:
      - main

jobs:
  check-tag:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if tag exists
        run: |
          git fetch --tags
          if git rev-parse v${{ env.VERSION }} >/dev/null 2>&1; then
            echo "Tag v${{ env.VERSION }} already exists"
            exit 1
          fi

  build-release:
    needs: check-tag
    runs-on: ubuntu-22.04

    env:
      QT_INSTALLER_JWT_TOKEN: ${{ secrets.QT_INSTALLER_JWT_TOKEN }}
      QT_VERSION: 6.7.1
      VERSION: 0.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make qt-version.txt
        run: |
          echo $QT_VERSION > qt-version.txt
          mkdir -p 3rdparty/Qt

      - name: Set up cache qt static
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: 3rdparty/Qt
          key: ${{ runner.os }}-qt-${{ hashFiles('qt-version.txt') }}
          restore-keys: |
            ${{ runner.os }}-qt-

      - if: ${{ steps.cache-qt.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: |
          ./scripts/setup --static

      - name: Install dependencies with cached Qt
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          ./scripts/setup --no-qt

      - name: Build project
        run: |
          ./scripts/configure
          cmake --build ./build --target package

      - name: Publish
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-linux"
          files: ./build/*.tar.gz

  build-windows-release:
    needs: check-tag
    runs-on: windows-latest

    env:
      QT_INSTALLER_JWT_TOKEN: ${{ secrets.QT_INSTALLER_JWT_TOKEN }}
      QT_VERSION: 6.7.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Make qt-version.txt
        run: |
          echo $QT_VERSION > qt-version.txt
          mkdir -p 3rdparty/Qt

      - name: Set up cache qt static
        id: cache-qt-window
        uses: actions/cache@v3
        with:
          path: 3rdparty/Qt
          key: ${{ runner.os }}-qt-${{ hashFiles('qt-version.txt') }}
          restore-keys: ${{ runner.os }}-qt-

      - if: ${{ steps.cache-qt-windows.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: |
          .\scripts\setup.ps1 --static

      - name: Build project
        run: |
          .\scripts\configure.ps1
          cmake --build ./build --config Release

      - name: Publish
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-windows"
          files: .\build\app\Release\*.exe

  push-tag:
    needs: [check-tag, build-release, build-windows-release]
    runs-on: ubuntu-22.04
    steps:
      - name: Push tag
        run: |
          git tag -a v${{ env.VERSION }} -m "Release v${{ env.VERSION }}"
          git push origin v${{ env.VERSION }}
    # push the files of both releases jobs to the release
