name: Release

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build-release:
    runs-on: ubuntu-22.04

    env:
      QT_INSTALLER_JWT_TOKEN: ${{ secrets.QT_INSTALLER_JWT_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          ./scripts/setup --static

      - name: Build project
        run: |
          ./scripts/configure
          cmake --build ./build --target package

      - name: Publish
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: ./build/*.tar.gz

  build-windows-release:
    runs-on: windows-latest

    env:
      QT_INSTALLER_JWT_TOKEN: ${{ secrets.QT_INSTALLER_JWT_TOKEN }}
      VSINSTALLDIR: C:\Program Files\Microsoft Visual Studio\2022\Enterprise

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          .\scripts\launch_dev_shell.ps1
          .\scripts\setup.ps1 --static

      - name: Build project
        run: |
          .\scripts\launch_dev_shell.ps1
          .\scripts\configure.ps1
          cmake --build ./build --target package --config Release

      - name: Publish
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: .\build\app\Release\*.exe
