name: Release

on:
  push:
    branches:
      - main

env:
  # By setting the RELEASE_VERSION environment variable, the version of the release can
  # be controlled. By pushing a tag with the same name as the RELEASE_VERSION, cmake
  # can use it to set the version of the project. The release should only be
  # created if no release with the same version exists. This can be checked by
  # visiting the corresponding url. We always run the build-release and
  # build-windows-release jobs, so the artifacts are always available for we
  # can check if the build was successful. The created artifacts are only
  # uploaded if a new release is created.
  RELEASE_VERSION: v0.1.0
  QT_INSTALLER_JWT_TOKEN: ${{ secrets.QT_INSTALLER_JWT_TOKEN }}
  QT_VERSION: 6.7.1

jobs:
  # This job is used to check if a release with the same version already
  # exists. If it does, terminate the job.
  check-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check release by url
        run: |
          release_url=$(curl -s https://api.github.com/repos/BartSte/trayicon/releases/tags/Release%200.0.0 | jq -r '.url')
          [[ "$release_url" == "null" ]]

  # The build-release job is used to build the project on a linux machine.
  build-release:
    needs: check-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make qt-version.txt
        run: |
          echo $QT_VERSION > qt-version.txt
          mkdir -p 3rdparty/Qt

      - name: Set up cache qt static
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: 3rdparty/Qt
          key: ${{ runner.os }}-qt-${{ hashFiles('qt-version.txt') }}
          restore-keys: |
            ${{ runner.os }}-qt-

      - if: ${{ steps.cache-qt.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: |
          ./scripts/setup --static

      - if: ${{ steps.cache-qt.outputs.cache-hit == 'true' }}
        name: Install dependencies with cached Qt
        run: |
          ./scripts/setup --no-qt

      - name: Build project
        run: |
          ./scripts/configure
          cmake --build ./build --target package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-tarball
          path: ./build/*.tar.gz

  # The build-windows-release job is used to build the project on a windows
  # machine.
  build-windows-release:
    needs: check-release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Make qt-version.txt
        run: |
          echo $QT_VERSION > qt-version.txt
          mkdir -p 3rdparty/Qt

      - name: Set up cache qt static
        id: cache-qt-window
        uses: actions/cache@v3
        with:
          path: 3rdparty/Qt
          key: ${{ runner.os }}-qt-${{ hashFiles('qt-version.txt') }}
          restore-keys: |
            ${{ runner.os }}-qt-

      - if: ${{ steps.cache-qt-windows.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: |
          .\scripts\setup.ps1 --static

      - if: ${{ steps.cache-qt-windows.outputs.cache-hit == 'true' }}
        name: Install dependencies with cached Qt
        run: |
          echo "Nothong to do!"

      - name: Build project
        run: |
          .\scripts\configure.ps1
          cmake --build ./build --config Release
          mv ./build/app/trayicon.exe ./build/app/trayicon-$RELEASE_VERSION.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-standalone-exe
          path: .\build\app\*.exe

  # If all jobs are successful, the make-release job is used to create the
  # release with tag $RELEASE_VERSION. The artifacts are downloaded from the
  # build jobs and uploaded to the release.
  make-release:
    needs: [check-release, build-release, build-windows-release]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            linux-tarball/*.tar.gz
            windows-standalone-exe/*.exe
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          body: |
            Release ${{ env.RELEASE_VERSION }}
            - [Changelog](https://github.com/BartSte/trayicon/CHANGELOG.md)
