name: Release

on:
  push:
    branches:
      - main

jobs:
  check-tag:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if tag exists
        run: |
          git fetch --tags
          if git rev-parse v${{ env.VERSION }} >/dev/null 2>&1; then
            echo "Tag v${{ env.VERSION }} already exists"
            exit 1
          fi

  build-release:
    needs: check-tag
    runs-on: ubuntu-22.04

    env:
      QT_INSTALLER_JWT_TOKEN: ${{ secrets.QT_INSTALLER_JWT_TOKEN }}
      QT_VERSION: 6.7.1
      VERSION: 0.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make qt-version.txt
        run: echo $QT_VERSION > qt-version.txt

      - name: Set up cache qt static
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: $PWD/3rdparty/Qt
          key: ${{ runner.os }}-qt-${{ hashFiles('qt-version.txt') }}
          restore-keys: |
            ${{ runner.os }}-qt-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          ./scripts/setup --static

      - name: Install dependencies with cached Qt
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          ./scripts/setup --no-qt

      - name: Build project
        run: |
          ./scripts/configure
          cmake --build ./build --target package

      - name: Publish
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: ./build/*.tar.gz

  build-windows-release:
    needs: check-tag
    runs-on: windows-latest

    env:
      QT_INSTALLER_JWT_TOKEN: ${{ secrets.QT_INSTALLER_JWT_TOKEN }}
      VSINSTALLDIR: C:\Program Files\Microsoft Visual Studio\2022\Enterprise
      QT_VERSION: 6.7.1
      CXX: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make qt-version.txt
        run: echo $QT_VERSION > qt-version.txt

      - name: Set up cache qt static
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: ./3rdparty/Qt
          key: ${{ runner.os }}-qt-${{ hashFiles('qt-version.txt') }}
          restore-keys: ${{ runner.os }}-qt-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          .\scripts\launch_dev_shell.ps1
          .\scripts\setup.ps1 --static

      - name: Build project
        run: |
          .\scripts\launch_dev_shell.ps1
          .\scripts\configure.ps1
          cmake --build ./build --target package --config Release

      - name: Publish
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: .\build\app\Release\*.exe

  push-tag:
    needs: [check-tag, build-release, build-windows-release]
    runs-on: ubuntu-22.04
    steps:
      - name: Push tag
        run: |
          git tag -a v${{ env.VERSION }} -m "Release v${{ env.VERSION }}"
          git push origin v${{ env.VERSION }}
